### ISSUE TITLE
public web site buckets?

### ISSUE THREAD

**Issue by pacohope** [kromtech/s3-inspector#13]
I ran this against my account. I have a few public buckets set up to be static web sites. That means the bucket name is something like `www.example.com` and so it's URL is `https://www.example.com`, not `https://www.example.com.s3.amazonaws.com`. I got this error when it tried to report on my bucket:

```
Bucket www.example.com: PUBLIC!
Location: eu-west-1
Permission: readable by Everyone
Traceback (most recent call last):
  File "s3inspector.py", line 332, in <module>
    main()
  File "s3inspector.py", line 328, in main
    analyze_buckets(s3, s3_client)
  File "s3inspector.py", line 197, in analyze_buckets
    urls = scan_bucket_urls(bucket.name)
  File "s3inspector.py", line 132, in scan_bucket_urls
    content = requests.get(url).text
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'www.example.com.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'
```

Sometimes public buckets are intended to be public because they're the static content part of a serverless web site. So
1. This script needs to not blow up on them
1. This script needs to account for that. Sometimes public buckets are deliberate. They have some good use cases.

**Comment by ze0adik** [comment]
Hi, we're sorry for late response.
We've fixed first described issue in 81ee927. 
We totally agree that public buckets have reasons to be used and we're planning to add option to whitelist such buckets later.
