### ISSUE TITLE
Issues when no public buckets exist

### ISSUE THREAD

**Issue by JasonOliverEmaze** [kromtech/s3-inspector#16]
Hi

Thanks for the awesome code, all works a treat when there are public buckets  in the accounts, however, when there are none I receive the following error:

[Errno 2] No such file or directory: '/tmp/report.txt': IOError
Traceback (most recent call last):
  File "/var/task/s3inspector.py", line 236, in lambda_handler
    send_report(report_path)
  File "/var/task/s3inspector.py", line 253, in send_report
    with open(path, "r") as f:
IOError: [Errno 2] No such file or directory: '/tmp/report.txt'

Lines 236, and 253 respectively...

236    send_report(report_path)
253    with open(path, "r") as f:

Is this something someone can help with?

Cheers, Jay

**Comment by JasonOliverEmaze** [comment]
I forgot to mention that I am running this as a Lambda function.
