### ISSUE TITLE
"raw_input not defined"

### ISSUE THREAD

**Issue by mozai** [kromtech/s3-inspector#20]
Steps to reproduce:
- python ./s3inspector.py

Seen:
```Traceback (most recent call last):
  File "./s3inspector.py", line 336, in <module>
    main()
  File "./s3inspector.py", line 331, in main
    s3, s3_client = get_s3_obj()
  File "./s3inspector.py", line 47, in get_s3_obj
    access_key = raw_input("Enter your AWS access key ID: ")
NameError: name 'raw_input' is not defined
```

Other info:  
Using python 3.6.5.  I can see in main() (line 326) that raw_input should have the built-in function input() assigned to it.  `assert(raw_input)` in main() does not fail but in `get_s3_obj()` the assertion fails.

Possible solution:  
Put `global raw_input` at the start of `def main()`.  Assignments in a function scope do not always propigate to sub-functions.

**Comment by maheshdighe** [comment]
Facing issue as below.
![image](https://user-images.githubusercontent.com/45825593/51245965-358e4c00-19af-11e9-9816-07ce9d4c675b.png)

**Comment by alinafe82** [comment]
⇒  ipython
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: raw_input("Enter your AWS profile name [default]: ") or "default"
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-fa614540d4da> in <module>()
----> 1 raw_input("Enter your AWS profile name [default]: ") or "default"

NameError: name 'raw_input' is not defined

In [2]: input("Enter your AWS profile name [default]: ") or "default"
Enter your AWS profile name [default]: default
Out[2]: 'default'

In [3]:

**Comment by maheshdighe** [comment]
Thanks...
I just kept **profile_name = "default"**  and it worked...

**Comment by sandromelobrazil** [comment]
I am having the same problem
Bucket mybucket.mydomain.xxx.xx: PUBLIC!
Location: sa-east-1
Permission: readable by Everyone
Traceback (most recent call last):
  File "s3inspector.py", line 336, in <module>
    main()
  File "s3inspector.py", line 332, in main
    analyze_buckets(s3, s3_client)
  File "s3inspector.py", line 201, in analyze_buckets
    urls = scan_bucket_urls(bucket.name)
  File "s3inspector.py", line 134, in scan_bucket_urls
    content = requests.get(url).text
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 424, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mybucket.mydomain.xxx.xx', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'mybucket.mydomain.xxx.xx' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'",),))

**Comment by sandromelobrazil** [comment]
To be honest, I don't know what happened because I had created the IAM account, SNS and Lambda funcions... but I ran the s3Inspector, it only get information from backet readonly, when it try to get information from specific bucket, it return a error...

**Comment by fontvu** [comment]
Hey I also got that problem. Instead of running in python 3, I installed boto3 by "pip2 install boto3". It worked afterwards.

**Comment by mozai** [comment]
Python 2.x is end-of-life in a few weeks, so using it with python2 is not an acceptable workaround.
