### ISSUE TITLE
Full of errors!

### ISSUE THREAD

**Issue by PrasBiswas** [kromtech/s3-inspector#28]
Traceback (most recent call last):
  File "s3inspector.py", line 106, in install_and_import
    importlib.import_module(pkg)
  File "C:\Program Files (x86)\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'termcolor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "s3inspector.py", line 109, in install_and_import
    pip.main(["install", pkg])
AttributeError: module 'pip' has no attribute 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "s3inspector.py", line 335, in <module>
    main()
  File "s3inspector.py", line 329, in main
    install_and_import(package)
  File "s3inspector.py", line 111, in install_and_import
    globals()[pkg] = importlib.import_module(pkg)
  File "C:\Program Files (x86)\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'termcolor'

**Comment by liebsen** [comment]
sudo apt install python-pip
pip install termcolor

**Comment by anuvindhs** [comment]
is this code still maintained,
am also getting similar error 
even after trying with the solution provided

Traceback (most recent call last):
  File "s3inspector.py", line 335, in <module>
    main()
  File "s3inspector.py", line 329, in main
    install_and_import(package)
  File "s3inspector.py", line 111, in install_and_import
    globals()[pkg] = importlib.import_module(pkg)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named boto3
